### ISSUE TITLE
Add more detailed description to show in Extensions Manager

### ISSUE THREAD

**Issue by coliff** [cezarywojcik/cezarywojcik.cleaner#2]
Right now this plugin has description of just 'Cleaner'. It'd be good if it displayed 'Removes trailing spaces and tabs, adds newlines at the end of the file, and converts tabs to spaces if the user is using spaces'

**Comment by coliff** [comment]
I just opened a pull request with the change to package.json

**Comment by xiangyuwu** [comment]
@coliff did you get any replies from the repo owner? Has this been perhaps taken up? Good suggestion by the way.

**Comment by coliff** [comment]
@xiangyuwu No I didn't hear anything back and there's been no updates to this project for 3 years.

**Comment by coliff** [comment]
@xiangyuwu it's updated now. :+1:
